(:METIS-SOURCE-KIT 1 :ID "cli-fix-demo" :NAME "CLI Fix Demo" :VERSION "1.0.0"
 :DESCRIPTION "" :LICENSE "MIT" :CATEGORY :SCIENCE :DEPENDS-ON NIL
 :CAPABILITIES NIL :BIBLIOGRAPHY NIL :CREATED "2026-08-07")
