;;;; ops.lisp — differentiable tensor operations
(in-package :metis.nn)

(defun %same-shape (a b)
  (equal (tns-shape a) (tns-shape b)))

(defun %broadcast-to (x shape)
  "Broadcast tensor X (or scalar tensor) to SHAPE (forward only storage)."
  (let* ((x (%as-tensor x))
         (xs (tns-shape x))
         (n (tensor-numel shape))
         (out (%make-storage n)))
    (cond
      ((equal xs shape)
       (tns-data x))
      ((= (tensor-numel xs) 1)
       (fill out (aref (tns-data x) 0))
       out)
      (t
       ;; last-dim broadcast only for common NN cases
       (assert (<= (length xs) (length shape)))
       (let ((xd (tns-data x)))
         (dotimes (i n)
           (setf (aref out i)
                 (aref xd (mod i (length xd))))))
       out))))

(defun t+ (a b)
  (let* ((a (%as-tensor a)) (b (%as-tensor b))
         (shape (if (>= (tensor-numel (tns-shape a))
                        (tensor-numel (tns-shape b)))
                    (tns-shape a) (tns-shape b)))
         (ad (%broadcast-to a shape))
         (bd (%broadcast-to b shape))
         (n (length ad))
         (data (%make-storage n))
         (rg (%binary-needs-grad a b)))
    (dotimes (i n) (setf (aref data i) (+ (aref ad i) (aref bd i))))
    (let ((out (make-tensor shape :requires-grad rg :data data)))
      (when rg
        (setf (tns-children out) (remove-if-not #'tensor-p (list a b)))
        (setf (tns-grad-fn out)
              (lambda (self)
                (let ((g (tns-grad self)))
                  (when (and (tensor-p a) (tns-requires-grad a))
                    (let ((ag (%ensure-grad a)))
                      (if (= (length ag) (length g))
                          (dotimes (i (length g)) (incf (aref ag i) (aref g i)))
                          (dotimes (i (length g)) (incf (aref ag 0) (aref g i))))))
                  (when (and (tensor-p b) (tns-requires-grad b))
                    (let ((bg (%ensure-grad b)))
                      (if (= (length bg) (length g))
                          (dotimes (i (length g)) (incf (aref bg i) (aref g i)))
                          (dotimes (i (length g)) (incf (aref bg 0) (aref g i))))))))))
      out)))

(defun t-neg (a)
  (let* ((a (%as-tensor a))
         (n (length (tns-data a)))
         (data (%make-storage n))
         (rg (%unary-needs-grad a)))
    (dotimes (i n) (setf (aref data i) (- (aref (tns-data a) i))))
    (let ((out (make-tensor (tns-shape a) :requires-grad rg :data data)))
      (when rg
        (setf (tns-children out) (list a))
        (setf (tns-grad-fn out)
              (lambda (self)
                (let ((g (tns-grad self)) (ag (%ensure-grad a)))
                  (dotimes (i (length g)) (decf (aref ag i) (aref g i)))))))
      out)))

(defun t- (a b) (t+ a (t-neg b)))

(defun t* (a b)
  "Elementwise multiply."
  (let* ((a (%as-tensor a)) (b (%as-tensor b))
         (shape (tns-shape a))
         (n (length (tns-data a)))
         (data (%make-storage n))
         (rg (%binary-needs-grad a b)))
    (assert (%same-shape a b) () "t* shape mismatch ~A ~A" (tns-shape a) (tns-shape b))
    (dotimes (i n)
      (setf (aref data i) (* (aref (tns-data a) i) (aref (tns-data b) i))))
    (let ((out (make-tensor shape :requires-grad rg :data data)))
      (when rg
        (setf (tns-children out) (list a b))
        (setf (tns-grad-fn out)
              (lambda (self)
                (let ((g (tns-grad self)))
                  (when (tns-requires-grad a)
                    (let ((ag (%ensure-grad a)) (bd (tns-data b)))
                      (dotimes (i n) (incf (aref ag i) (* (aref g i) (aref bd i))))))
                  (when (tns-requires-grad b)
                    (let ((bg (%ensure-grad b)) (ad (tns-data a)))
                      (dotimes (i n) (incf (aref bg i) (* (aref g i) (aref ad i))))))))))
      out)))

(defun t-sum (a &key (axis nil))
  (declare (ignore axis))
  (let* ((a (%as-tensor a))
         (s 0d0)
         (rg (%unary-needs-grad a)))
    (loop for x across (tns-data a) do (incf s x))
    (let ((out (make-tensor '(1) :requires-grad rg :init s)))
      (when rg
        (setf (tns-children out) (list a))
        (setf (tns-grad-fn out)
              (lambda (self)
                (let ((g (aref (tns-grad self) 0))
                      (ag (%ensure-grad a)))
                  (dotimes (i (length ag)) (incf (aref ag i) g))))))
      out)))

(defun t-mean (a)
  (let ((n (length (tns-data (%as-tensor a)))))
    (t* (t-sum a) (make-tensor '(1) :init (/ 1d0 n)))))

(defun %matmul-forward-data (ad bd m k n)
  "Forward matmul storage via active symbols NN backend when available."
  (if (and (find-package :metis.symbols)
           (fboundp (find-symbol "NN-BACKEND-MATMUL" :metis.symbols))
           (fboundp (find-symbol "ACTIVE-NN-BACKEND" :metis.symbols)))
      (funcall (symbol-function (find-symbol "NN-BACKEND-MATMUL" :metis.symbols))
               (funcall (symbol-function (find-symbol "ACTIVE-NN-BACKEND" :metis.symbols)))
               ad bd m k n)
      ;; pure inline CPU fallback (substrate always works)
      (let ((data (%make-storage (* m n))))
        (dotimes (i m)
          (dotimes (j n)
            (let ((s 0d0))
              (dotimes (t0 k)
                (incf s (* (aref ad (+ (* i k) t0))
                           (aref bd (+ (* t0 n) j)))))
              (setf (aref data (+ (* i n) j)) s))))
        data)))

(defun t-matmul (a b)
  "Matrix multiply (m,k)·(k,n) → (m,n). Forward path uses the active
   symbols NN backend (cpu-nn or gpu-nn). Backward remains on host."
  (let* ((a (%as-tensor a)) (b (%as-tensor b))
         (as (tns-shape a)) (bs (tns-shape b))
         (ad (tns-data a)) (bd (tns-data b))
         (rg (%binary-needs-grad a b)))
    (cond
      ((and (= (length as) 2) (= (length bs) 2))
       (destructuring-bind (m k) as
         (destructuring-bind (k2 n) bs
           (assert (= k k2) () "matmul inner dim ~A vs ~A" k k2)
           (let ((data (%matmul-forward-data ad bd m k n)))
             (let ((out (make-tensor (list m n) :requires-grad rg :data data)))
               (when rg
                 (setf (tns-children out) (list a b))
                 (setf (tns-grad-fn out)
                       (lambda (self)
                         (let ((g (tns-grad self)))
                           (when (tns-requires-grad a)
                             (let ((ag (%ensure-grad a)))
                               (dotimes (i m)
                                 (dotimes (t0 k)
                                   (let ((s 0d0))
                                     (dotimes (j n)
                                       (incf s (* (aref g (+ (* i n) j))
                                                  (aref bd (+ (* t0 n) j)))))
                                     (incf (aref ag (+ (* i k) t0)) s))))))
                           (when (tns-requires-grad b)
                             (let ((bg (%ensure-grad b)))
                               (dotimes (t0 k)
                                 (dotimes (j n)
                                   (let ((s 0d0))
                                     (dotimes (i m)
                                       (incf s (* (aref ad (+ (* i k) t0))
                                                  (aref g (+ (* i n) j)))))
                                     (incf (aref bg (+ (* t0 n) j)) s))))))))))
               out)))))
      (t (error "matmul unsupported shapes ~A ~A" as bs)))))

(defun t-transpose (a)
  (let* ((a (%as-tensor a))
         (as (tns-shape a)))
    (assert (= (length as) 2))
    (destructuring-bind (m n) as
      (let ((data (%make-storage (* m n)))
            (ad (tns-data a))
            (rg (%unary-needs-grad a)))
        (dotimes (i m)
          (dotimes (j n)
            (setf (aref data (+ (* j m) i)) (aref ad (+ (* i n) j)))))
        (let ((out (make-tensor (list n m) :requires-grad rg :data data)))
          (when rg
            (setf (tns-children out) (list a))
            (setf (tns-grad-fn out)
                  (lambda (self)
                    (let ((g (tns-grad self)) (ag (%ensure-grad a)))
                      (dotimes (i m)
                        (dotimes (j n)
                          (incf (aref ag (+ (* i n) j))
                                (aref g (+ (* j m) i)))))))))
          out)))))

(defun %relu-forward-data (ad n)
  "Forward ReLU via active symbols NN backend when available."
  (if (and (find-package :metis.symbols)
           (fboundp (find-symbol "NN-BACKEND-RELU" :metis.symbols))
           (fboundp (find-symbol "ACTIVE-NN-BACKEND" :metis.symbols)))
      (funcall (symbol-function (find-symbol "NN-BACKEND-RELU" :metis.symbols))
               (funcall (symbol-function (find-symbol "ACTIVE-NN-BACKEND" :metis.symbols)))
               ad n)
      (let ((data (%make-storage n)))
        (dotimes (i n) (setf (aref data i) (max 0d0 (aref ad i))))
        data)))

(defun t-relu (a)
  (let* ((a (%as-tensor a))
         (n (length (tns-data a)))
         (ad (tns-data a))
         (data (%relu-forward-data ad n))
         (rg (%unary-needs-grad a)))
    (let ((out (make-tensor (tns-shape a) :requires-grad rg :data data)))
      (when rg
        (setf (tns-children out) (list a))
        (setf (tns-grad-fn out)
              (lambda (self)
                (let ((g (tns-grad self)) (ag (%ensure-grad a)))
                  (dotimes (i n)
                    (when (> (aref ad i) 0d0)
                      (incf (aref ag i) (aref g i))))))))
      out)))

(defun t-softmax (a)
  "Softmax over last dimension. Shape (batch, n) or (n)."
  (let* ((a (%as-tensor a))
         (as (tns-shape a))
         (ad (tns-data a))
         (rg (%unary-needs-grad a)))
    (labels ((row-softmax (start n out-data)
               (let ((maxv most-negative-double-float))
                 (dotimes (j n)
                   (setf maxv (max maxv (aref ad (+ start j)))))
                 (let ((sum 0d0))
                   (dotimes (j n)
                     (let ((e (exp (- (aref ad (+ start j)) maxv))))
                       (setf (aref out-data (+ start j)) e)
                       (incf sum e)))
                   (dotimes (j n)
                     (setf (aref out-data (+ start j))
                           (/ (aref out-data (+ start j)) sum)))))))
      (let ((data (%make-storage (length ad))))
        (if (= (length as) 1)
            (row-softmax 0 (first as) data)
            (destructuring-bind (batch n) as
              (dotimes (i batch) (row-softmax (* i n) n data))))
        (let ((out (make-tensor as :requires-grad rg :data data)))
          (when rg
            (setf (tns-children out) (list a))
            (setf (tns-grad-fn out)
                  (lambda (self)
                    ;; dL/dx_i = y_i * (dL/dy_i - sum_j dL/dy_j * y_j)
                    (let ((g (tns-grad self))
                          (ag (%ensure-grad a))
                          (y data))
                      (flet ((row (start n)
                               (let ((dot 0d0))
                                 (dotimes (j n)
                                   (incf dot (* (aref g (+ start j))
                                                (aref y (+ start j)))))
                                 (dotimes (j n)
                                   (incf (aref ag (+ start j))
                                         (* (aref y (+ start j))
                                            (- (aref g (+ start j)) dot)))))))
                        (if (= (length as) 1)
                            (row 0 (first as))
                            (destructuring-bind (batch n) as
                              (dotimes (i batch) (row (* i n) n)))))))))
          out)))))

(defun t-cross-entropy (logits targets)
  "logits (batch, nclass), targets list/vector of integer class indices → scalar mean NLL."
  (let* ((logits (%as-tensor logits))
         (ls (tns-shape logits)))
    (assert (= (length ls) 2))
    (destructuring-bind (batch nclass) ls
      (let* ((ld (tns-data logits))
             (tgts (if (vectorp targets) targets
                       (coerce targets 'vector)))
             (loss 0d0)
             (rg (%unary-needs-grad logits))
             ;; store softmax for backward
             (probs (%make-storage (* batch nclass))))
        (assert (= (length tgts) batch))
        (dotimes (i batch)
          (let* ((start (* i nclass))
                 (maxv most-negative-double-float)
                 (sum 0d0)
                 (ti (aref tgts i)))
            (dotimes (j nclass)
              (setf maxv (max maxv (aref ld (+ start j)))))
            (dotimes (j nclass)
              (let ((e (exp (- (aref ld (+ start j)) maxv))))
                (setf (aref probs (+ start j)) e)
                (incf sum e)))
            (dotimes (j nclass)
              (setf (aref probs (+ start j)) (/ (aref probs (+ start j)) sum)))
            (decf loss (log (max 1d-12 (aref probs (+ start ti)))))))
        (setf loss (/ loss batch))
        (let ((out (make-tensor '(1) :requires-grad rg :init loss)))
          (when rg
            (setf (tns-children out) (list logits))
            (setf (tns-grad-fn out)
                  (lambda (self)
                    (let ((scale (aref (tns-grad self) 0))
                          (ag (%ensure-grad logits)))
                      (dotimes (i batch)
                        (let ((start (* i nclass))
                              (ti (aref tgts i)))
                          (dotimes (j nclass)
                            (let ((g (/ (aref probs (+ start j)) batch)))
                              (when (= j ti) (decf g (/ 1d0 batch)))
                              (incf (aref ag (+ start j)) (* scale g))))))))))
          out)))))

(defun t-mse (pred target)
  (let* ((pred (%as-tensor pred))
         (target (%as-tensor target))
         (n (length (tns-data pred)))
         (data (%make-storage n))
         (rg (%binary-needs-grad pred target)))
    (dotimes (i n)
      (let ((d (- (aref (tns-data pred) i) (aref (tns-data target) i))))
        (setf (aref data i) (* d d))))
    (let* ((sq (make-tensor (tns-shape pred) :requires-grad rg :data data))
           (out (t-mean sq)))
      ;; rewire grad for pred
      (when (tns-requires-grad pred)
        (setf (tns-children out) (list pred target))
        (let ((old-fn (tns-grad-fn out)))
          (setf (tns-grad-fn out)
                (lambda (self)
                  (declare (ignore old-fn))
                  (let ((scale (/ (aref (tns-grad self) 0) n))
                        (ag (%ensure-grad pred))
                        (pd (tns-data pred))
                        (td (tns-data target)))
                    (dotimes (i n)
                      (incf (aref ag i)
                            (* scale 2d0 (- (aref pd i) (aref td i))))))))))
      out)))

(defun t-embedding-lookup (weight indices)
  "weight (vocab, dim), indices list/vector of ints → (batch, dim) or (seq, dim)."
  (let* ((w (%as-tensor weight))
         (ws (tns-shape w)))
    (assert (= (length ws) 2))
    (destructuring-bind (vocab dim) ws
      (let* ((idx (if (vectorp indices) indices (coerce indices 'vector)))
             (batch (length idx))
             (data (%make-storage (* batch dim)))
             (wd (tns-data w))
             (rg (and *grad-enabled* (tns-requires-grad w))))
        (dotimes (i batch)
          (let ((id (aref idx i)))
            (assert (and (>= id 0) (< id vocab)))
            (dotimes (j dim)
              (setf (aref data (+ (* i dim) j))
                    (aref wd (+ (* id dim) j))))))
        (let ((out (make-tensor (list batch dim) :requires-grad rg :data data)))
          (when rg
            (setf (tns-children out) (list w))
            (setf (tns-grad-fn out)
                  (lambda (self)
                    (let ((g (tns-grad self)) (wg (%ensure-grad w)))
                      (dotimes (i batch)
                        (let ((id (aref idx i)))
                          (dotimes (j dim)
                            (incf (aref wg (+ (* id dim) j))
                                  (aref g (+ (* i dim) j))))))))))
          out)))))

(defun t-causal-context-mean (x &key (window nil))
  "Causal context pool over last WINDOW positions.

   X shape (T, D). For each t, output[t] = mean(X[max(0,t-W+1) .. t]).
   WINDOW defaults to T (full prefix). Differentiable. This is the live
   context-window path used by the multi-layer language model."
  (let* ((x (%as-tensor x))
         (xs (tns-shape x)))
    (assert (= (length xs) 2) () "t-causal-context-mean expects (T,D), got ~A" xs)
    (destructuring-bind (tt dim) xs
      (let* ((w (min tt (or window tt)))
             (ad (tns-data x))
             (data (%make-storage (* tt dim)))
             (counts (make-array tt :element-type 'fixnum))
             (rg (%unary-needs-grad x)))
        (dotimes (t0 tt)
          (let* ((start (max 0 (1+ (- t0 w))))
                 (cnt (1+ (- t0 start))))
            (setf (aref counts t0) cnt)
            (dotimes (j dim)
              (let ((s 0d0))
                (loop for i from start to t0
                      do (incf s (aref ad (+ (* i dim) j))))
                (setf (aref data (+ (* t0 dim) j)) (/ s cnt))))))
        (let ((out (make-tensor xs :requires-grad rg :data data)))
          (when rg
            (setf (tns-children out) (list x))
            (setf (tns-grad-fn out)
                  (lambda (self)
                    (let ((g (tns-grad self))
                          (ag (%ensure-grad x)))
                      (dotimes (t0 tt)
                        (let* ((start (max 0 (1+ (- t0 w))))
                               (scale (/ 1d0 (aref counts t0))))
                          (loop for i from start to t0
                                do (dotimes (j dim)
                                     (incf (aref ag (+ (* i dim) j))
                                           (* scale (aref g (+ (* t0 dim) j))))))))))))
          out)))))
