(:METIS-SOURCE-KIT 1 :ID "guide-min" :NAME "guide-min" :VERSION "1.0.0"
 :DESCRIPTION "" :LICENSE "CC-BY-4.0" :CATEGORY :SCIENCE :DEPENDS-ON NIL
 :CAPABILITIES NIL :BIBLIOGRAPHY NIL :CREATED "2026-08-07")
