#!/usr/bin/env bash
# Metis installer — source tree + launcher (SBCL + Quicklisp product).
#
# One-liner:
#   curl -fsSL https://metis.f00.sh/install.sh | bash
#   curl -fsSL https://github.com/f00-sh/metis/releases/latest/download/install.sh | bash
#
# Local checkout:
#   ./scripts/install.sh
#   PREFIX=/opt/metis ./scripts/install.sh
#
# Env:
#   PREFIX / INSTALL_PREFIX   install root (default: ~/.local)
#   METIS_VERSION             release tag/version pin (default: latest)
#   METIS_REPO                owner/repo (default: f00-sh/metis)
#   METIS_FROM_RELEASE=1      force download even inside a git checkout
#   METIS_LOCAL=1             force local-tree install
#   METIS_SKIP_QL_LINK=1      do not symlink into ~/quicklisp/local-projects
#   METIS_NO_MAN=1            skip man page
set -euo pipefail

PROJECT="metis"
REPO="${METIS_REPO:-f00-sh/metis}"
PREFIX="${PREFIX:-${INSTALL_PREFIX:-${HOME}/.local}}"
BIN_DIR="${INSTALL_BIN_DIR:-${PREFIX}/bin}"
SHARE_DIR="${INSTALL_SHARE_DIR:-${PREFIX}/share/${PROJECT}}"
MAN_DIR="${INSTALL_MAN_DIR:-${PREFIX}/share/man/man1}"
EDGE_INSTALL_URL="${METIS_EDGE_INSTALL:-https://metis.f00.sh/install.sh}"

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"; }

need mkdir
need install
need cp
need find

SCRIPT_PATH="${BASH_SOURCE[0]:-$0}"
# When piped (curl | bash), BASH_SOURCE may be empty or /dev/fd/* — no local root.
ROOT=""
if [[ -n "${SCRIPT_PATH}" && -f "${SCRIPT_PATH}" && "${SCRIPT_PATH}" != /dev/fd/* && "${SCRIPT_PATH}" != /proc/self/fd/* ]]; then
  ROOT="$(cd "$(dirname "${SCRIPT_PATH}")/.." 2>/dev/null && pwd || true)"
fi

is_metis_tree() {
  local d="$1"
  [[ -n "$d" && -f "${d}/metis.asd" && -x "${d}/bin/metis" && -f "${d}/VERSION" ]]
}

path_hint() {
  case ":${PATH}:" in
    *":${BIN_DIR}:"*) ;;
    *)
      printf '\nAdd to PATH:\n  export PATH="%s:$PATH"\n' "${BIN_DIR}" >&2
      ;;
  esac
}

link_quicklisp() {
  [[ "${METIS_SKIP_QL_LINK:-0}" == "1" ]] && return 0
  local ql="${HOME}/quicklisp/local-projects"
  [[ -d "${HOME}/quicklisp" ]] || return 0
  mkdir -p "${ql}"
  ln -sfn "${SHARE_DIR}" "${ql}/metis"
  printf 'quicklisp local-projects: %s/metis -> %s\n' "${ql}" "${SHARE_DIR}"
}

install_tree_from() {
  local src="$1"
  is_metis_tree "${src}" || die "not a Metis tree: ${src}"

  mkdir -p "${SHARE_DIR}" "${BIN_DIR}" "${MAN_DIR}"
  # Fresh share tree (keep user ~/.metis data outside prefix share)
  find "${SHARE_DIR}" -mindepth 1 -maxdepth 1 -exec rm -rf {} + 2>/dev/null || true

  if command -v rsync >/dev/null 2>&1; then
    rsync -a \
      --exclude '.git/' \
      --exclude '.wrangler/' \
      --exclude 'models/**' \
      --exclude 'packaging/out/' \
      --exclude 'build/' \
      --exclude '*.fasl' \
      "${src}/" "${SHARE_DIR}/"
  else
    # Portable fallback: copy essential product surface
    for item in bin src knowledge symbols tests docs man site \
                metis.asd VERSION LICENSE README.md CHANGELOG.md \
                file_id.diz metis.conf.example packaging AGENTS.md; do
      if [[ -e "${src}/${item}" ]]; then
        cp -a "${src}/${item}" "${SHARE_DIR}/"
      fi
    done
  fi

  chmod +x "${SHARE_DIR}/bin/metis" "${SHARE_DIR}/bin/symbol" 2>/dev/null || true
  if [[ -f "${SHARE_DIR}/scripts/install.sh" ]]; then
    chmod +x "${SHARE_DIR}/scripts/install.sh"
  fi

  # Launcher in PREFIX/bin → installed tree
  cat > "${BIN_DIR}/metis" <<EOF
#!/usr/bin/env bash
# Generated by Metis install.sh — do not edit; re-run installer to refresh.
set -euo pipefail
export METIS_ROOT="${SHARE_DIR}"
export CL_SOURCE_REGISTRY="\${METIS_ROOT}/:\${CL_SOURCE_REGISTRY:-}"
exec "\${METIS_ROOT}/bin/metis" "\$@"
EOF
  chmod 0755 "${BIN_DIR}/metis"

  if [[ "${METIS_NO_MAN:-0}" != "1" ]]; then
    if [[ -f "${SHARE_DIR}/man/metis.1" ]]; then
      install -m 0644 "${SHARE_DIR}/man/metis.1" "${MAN_DIR}/metis.1"
    elif [[ -f "${src}/man/metis.1" ]]; then
      install -m 0644 "${src}/man/metis.1" "${MAN_DIR}/metis.1"
    fi
  fi

  link_quicklisp

  local ver
  ver="$(tr -d '[:space:]' < "${SHARE_DIR}/VERSION" 2>/dev/null || echo unknown)"
  printf '\ninstalled Metis %s\n' "${ver}"
  printf '  prefix:  %s\n' "${PREFIX}"
  printf '  tree:    %s\n' "${SHARE_DIR}"
  printf '  launcher:%s/metis\n' "${BIN_DIR}"
  path_hint
  printf 'verify:  %s/metis version\n' "${BIN_DIR}"
  printf 'run:     %s/metis          # TUI\n' "${BIN_DIR}"
  printf 'docs:    https://metis.f00.sh/\n'
}

resolve_tag() {
  if [[ -n "${METIS_VERSION:-}" ]]; then
    local t="${METIS_VERSION}"
    t="${t#v}"
    echo "${t}"
    return
  fi
  need curl
  local tag
  tag="$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" \
    | sed -n 's/.*"tag_name": *"\([^"]*\)".*/\1/p' | head -1 || true)"
  [[ -n "${tag}" ]] || die "could not resolve latest release; set METIS_VERSION=X.Y.Z"
  echo "${tag#v}"
}

install_release() {
  need curl
  need tar
  local ver tmp url
  ver="$(resolve_tag)"
  tmp="$(mktemp -d)"
  # shellcheck disable=SC2064
  trap 'rm -rf "${tmp:-/tmp/metis-install-none}"' EXIT
  # Prefer release asset (stable sha for brew/AUR), then GitHub tag archive.
  url="https://github.com/${REPO}/releases/download/${ver}/metis-${ver}-src.tar.gz"
  printf 'downloading %s\n' "${url}"
  if ! curl -fsSL "${url}" -o "${tmp}/metis.tar.gz"; then
    url="https://github.com/${REPO}/archive/refs/tags/${ver}.tar.gz"
    printf 'retry tag archive %s\n' "${url}"
    if ! curl -fsSL "${url}" -o "${tmp}/metis.tar.gz"; then
      url="https://github.com/${REPO}/archive/refs/tags/v${ver}.tar.gz"
      printf 'retry %s\n' "${url}"
      curl -fsSL "${url}" -o "${tmp}/metis.tar.gz" \
        || die "release source archive missing (${url})"
    fi
  fi
  tar -C "${tmp}" -xzf "${tmp}/metis.tar.gz"
  local extracted
  extracted="$(find "${tmp}" -maxdepth 1 -type d -name 'metis-*' | head -1)"
  [[ -n "${extracted}" ]] || die "tarball extract failed"
  install_tree_from "${extracted}"
  trap - EXIT
  rm -rf "${tmp}"
}

# Decide mode
if [[ "${METIS_FROM_RELEASE:-0}" == "1" ]]; then
  install_release
elif [[ "${METIS_LOCAL:-0}" == "1" ]]; then
  is_metis_tree "${ROOT}" || die "METIS_LOCAL=1 but not inside a Metis checkout"
  install_tree_from "${ROOT}"
elif is_metis_tree "${ROOT}"; then
  install_tree_from "${ROOT}"
else
  install_release
fi

# Health check (non-fatal if SBCL missing — launcher still installed)
if [[ -x "${BIN_DIR}/metis" ]]; then
  if out="$("${BIN_DIR}/metis" version 2>/dev/null)"; then
    printf 'health: %s\n' "${out}"
  else
    printf 'note: launcher installed; run with SBCL+Quicklisp: %s/metis version\n' "${BIN_DIR}" >&2
  fi
fi
