;;;; language.lisp — s-expression mind language (tell / ask / pursue / …)
(in-package :metis)

(defun interpret (mind form)
  "Interpret a Metis mind-language form. Returns result value."
  (mind-trace-push mind :interpret form)
  (cond
    ((null form) nil)
    ((stringp form)
     (interpret mind (read-from-string form)))
    ((not (consp form))
     (ask mind form))
    (t
     (let ((op (car form))
           (args (cdr form)))
       (case op
         ((quit exit) :quit)
         ((status) (mind-status mind))
         ((help)
          '(tell ask ask-all prove assert retract rule
            goal pursue plan htn do tool reflect explain self
            remember recall skills forward boot save load
            llm cycle interpret eval tx society api daemon
            why production-boot version))
         ((tell assert)
          (dolist (f args) (assert-fact mind f))
          :ok)
         ((retract)
          (mapcar (lambda (f) (retract-fact mind f)) args))
         ((rule <-)
          ;; (rule head body1 body2...) or (rule name head <- body...)
          (cond
            ((and (symbolp (first args))
                  (find '<- args))
             (let* ((name (first args))
                    (arrow (position '<- args))
                    (head (nth (1- arrow) args))
                    (body (subseq args (1+ arrow))))
               (assert-rule mind head body :name name)))
            (t
             (assert-rule mind (first args) (rest args)))))
         ((ask)
          (if (rest args)
              (mapcar (lambda (p) (ask mind p)) args)
              (ask mind (first args))))
         ((ask-all)
          (ask-all mind (first args)))
         ((prove)
          (multiple-value-list (prove (first args) :kb (mind-kb mind))))
         ((forward)
          (forward-chain mind))
         ((goal)
          (apply #'goal-push mind args)
          (mind-goals mind))
         ((pursue)
          (pursue mind (if (rest args) args (first args))))
         ((plan)
          (plan mind (if (and (consp (first args))
                              (not (symbolp (car (first args)))))
                         (first args)
                         args)))
         ((htn)
          (htn-plan mind (if (rest args) args (first args)) :execute t))
         ((why)
          (explain-deep mind (if (rest args) args (first args))))
         ((version)
          (metis-version-string))
         ((production-boot)
          (production-boot :api (member :api args)
                           :daemon (member :daemon args)
                           :society (member :society args)))
         ((society)
          (case (first args)
            ((boot ensemble) (society-default-ensemble))
            ((step) (society-step *society*))
            ((status) (and *society*
                           (mapcar #'mind-name (society-minds *society*))))
            (t (society-default-ensemble))))
         ((api)
          (case (first args)
            ((start) (api-start))
            ((stop) (api-stop))
            (t (api-status))))
         ((daemon)
          (case (first args)
            ((start) (daemon-start))
            ((stop) (daemon-stop))
            (t (daemon-status))))
         ((do execute)
          (act mind (first args) (rest args)))
         ((tool)
          (apply #'invoke-tool mind (first args) (rest args)))
         ((reflect)
          (reflect mind (first args)))
         ((explain)
          (explain mind (first args)))
         ((self self-model)
          (self-model mind))
         ((remember)
          (remember-episode mind
                            :situation (first args)
                            :outcome (second args)
                            :tags (third args)))
         ((recall)
          (recall-episodes mind :pattern (first args) :limit 20))
         ((skills)
          (find-skills mind))
         ((synthesize-skill)
          (synthesize-skill mind (first args) (second args)
                            :preconds (third args)))
         ((rewrite-rule)
          (rewrite-rule mind (first args) (second args) (third args)))
         ((cycle)
          (cognitive-cycle mind))
         ((run-once)
          (run-once mind))
         ((llm)
          (if (llm-enabled-p)
              (llm-reason mind (if (stringp (first args))
                                   (first args)
                                   (prin1-to-string args)))
              '(:error "LLM disabled — set METIS_LLM_API_KEY and (set-config :llm-enabled t)")))
         ((eval)
          (eval-in-mind mind (first args)))
         ((save)
          (save-world mind (or (first args) "default")))
         ((load)
          (load-world mind (or (first args) "default")))
         ((frame deframe)
          (apply #'deframe mind (first args) (rest args)))
         ((frame-get)
          (frame-get mind (first args) (second args)))
         ((frame-set)
          (frame-set mind (first args) (second args) (third args)))
         ((working)
          (working-contents mind))
         ((trace)
          (reason-trace mind (or (first args) 40)))
         (t
          ;; treat unknown as fact query or assert?
          (if (and (= (length form) 1) (symbolp (car form)))
              (ask mind form)
              (progn
                (assert-fact mind form)
                form))))))))
