;;;; package.lisp — Metis public surface (production 1.0)
(defpackage :metis
  (:use :cl :alexandria)
  (:export
   ;; version / lifecycle
   #:*metis-version*
   #:metis-version-string
   #:metis-build-info
   #:metis-error
   #:metis-error-message
   #:boot
   #:reset-mind
   #:run
   #:run-once
   #:production-boot
   ;; knowledge
   #:assert-fact
   #:retract-fact
   #:assert-rule
   #:facts
   #:rules
   #:tell
   #:ask
   #:ask-all
   #:prove
   #:forward-chain
   ;; frames
   #:deframe
   #:frame-get
   #:frame-set
   #:frame-slots
   #:all-frames
   ;; planning
   #:define-operator
   #:plan
   #:execute-plan
   #:htn-plan
   #:htn-defmethod
   #:htn-defprimitive
   ;; memory / learning
   #:remember-episode
   #:recall-episodes
   #:install-skill
   #:find-skills
   #:working-add
   #:working-contents
   #:learn-from-plan
   #:reinforce-skill
   ;; TMS / belief
   #:tms-why
   #:tms-in-p
   #:tms-assert
   #:tms-retract-assumption
   #:tms-in-facts
   #:belief-get
   #:belief-set
   #:belief-query
   ;; introspection / meta / explain
   #:reflect
   #:explain
   #:explain-deep
   #:explain-fact
   #:self-model
   #:reason-trace
   #:synthesize-skill
   #:mind-status
   #:rewrite-rule
   #:eval-in-mind
   #:sandboxed-eval
   ;; agent cycle
   #:perceive
   #:deliberate
   #:act
   #:cognitive-cycle
   #:pursue
   #:goal-push
   #:goal-pop
   #:current-goals
   ;; multi-agent
   #:society-boot
   #:society-default-ensemble
   #:society-register
   #:society-send
   #:society-broadcast
   #:society-step
   #:society-run-cycles
   #:society-start-async
   #:society-stop
   #:*society*
   #:bb-post
   #:bb-read
   ;; tools / llm
   #:register-tool
   #:invoke-tool
   #:list-tools
   #:llm-complete
   #:llm-enabled-p
   ;; language / world / tx
   #:interpret
   #:save-world
   #:load-world
   #:tx-begin
   #:tx-assert
   #:tx-retract
   #:tx-commit
   #:tx-rollback
   #:with-mind-transaction
   ;; daemon / API
   #:daemon-start
   #:daemon-stop
   #:daemon-status
   #:api-start
   #:api-stop
   #:api-status
   ;; config / log
   #:*config*
   #:*mind*
   #:get-config
   #:set-config
   #:metis-log
   #:recent-logs
   #:log-set-level
   #:csp-solve
   #:security-profile
   ;; 2.0 further paths
   #:rete-compile
   #:run-forward-rete
   #:forward-chain-rete
   #:rete-assert-wme
   #:rete-assert-fact
   #:rete-invalidate
   #:durable-open
   #:durable-close
   #:durable-put
   #:durable-get
   #:durable-save-mind
   #:durable-load-mind
   #:durable-roundtrip-ok-p
   #:tms-formal-verify
   #:load-large-corpus
   #:arc-boot
   #:arc-cycle
   #:arc-status
   #:arc-thesis
   #:*arc*
   #:api-security-check-input
   #:api-require-auth
   ;; 3.0 EPOCH
   #:epoch-thesis
   #:epoch-open
   #:epoch-step
   #:epoch-run
   #:epoch-suspend
   #:epoch-resume
   #:epoch-status
   #:epoch-flagship
   #:epoch-guarded-self-mod
   #:epoch-ingest-self-code
   #:epoch-leap-resume-demo
   #:*epoch*
   #:*epoch-thesis*
   ;; 3.1 interactive interface
   #:session-create
   #:session-ensure
   #:session-get
   #:session-attach-file
   #:session-attach-photo
   #:session-attach-context
   #:session-attach-folder
   #:session-ingest-path
   #:session-train-on-text!
   #:session-watch-folder
   #:session-watch-poll!
   #:brain-start!
   #:brain-stop!
   #:brain-status
   #:brain-enqueue-train!
   #:brain-queue-depth
   #:*brain-auto-start*
   #:*brain-interval*
   #:*session-folder-watches*
   #:extract-text-from-path
   #:session-list-attachments
   #:session-get-attachment
   #:session-attachment-text
   #:session-status
   #:*session*
   #:iface-turn
   #:iface-drive
   #:iface-repl
   #:iface-accommodate
   #:iface-flagship
   #:iface-thesis
   #:iface-tokenize-query
   #:iface-retrieve-attachments
   #:iface-extractive-answer
   #:iface-rank-sentences
   #:iface-split-sentences
   #:iface-freeform-answer
   #:eval-math-expression
   #:llm-complete
   #:llm-enabled-p
   #:configure-llm!
   #:llm-status
   #:llm-save-key!
   #:llm-clear-key!
   #:llm-set-model!
   #:llm-set-base-url!
   #:llm-keyfile-path
   #:load-dotenv
   #:*iface-thesis*
   ;; product TUI (pure Common Lisp, ANSI/Unicode)
   #:tui-run
   #:run-tui
   #:tui-splash
   #:*tui-use-color*
   #:*tui-use-unicode*
   #:*tui-quit-process*
   ;; 4.0 neural substrate (pure CL) + continuous train + TMS gate
   #:nn-train-language-model
   #:nn-train-file
   #:nn-continuous-train
   #:nn-train-from-session
   #:session-corpus
   #:nn-generate
   #:nn-train-mlp-xor
   #:nn-enable-path
   #:nn-disable-path
   #:nn-path-allowed-p
   #:nn-check-path!
   #:*nn-path-fact*
   #:install-nn-tools
   ;; 4.1 symbols (plugins) + NN backend
   #:symbols-boot!
   #:discover-symbols!
   #:symbol-list
   #:symbol-list-info
   #:symbol-info
   #:load-symbol!
   #:enable-symbol!
   #:disable-symbol!
   #:install-symbol!
   #:nn-backend-status
   #:install-symbol-tools
   #:chat-ui-summary
   #:chat-ui-transcript
   #:image-ingest-session
   #:domain-pack-load
   #:curriculum-apply
   #:sign-symbol-package
   #:verify-symbol-package
   ;; open-knowledge hybrid symbol packs
   #:make-symbol-pack-manifest
   #:symbol-pack-validate-manifest
   #:symbol-pack-write!
   #:symbol-pack-load-into-mind!
   #:symbol-export-snapshot!
   #:symbol-import-snapshot!
   #:symbol-pack-install!
   #:symbol-pack-enable!
   #:symbol-pack-disable!
   #:symbol-pack-overlay-unload!
   #:symbol-pack-catalog
   #:symbol-pack-catalog-install
   #:symbol-pack-ensure-seeds!
   #:symbol-pack-boot!
   #:symbol-pack-list-installed
   #:symbol-pack-query
   #:symbol-pack-query-all
   #:symbol-pack-clear-layers!
   #:*symbol-pack-overlays*
   #:*symbol-pack-layer-store*
   #:*symbol-pack-fact-refcount*
   #:*symbol-pack-base-pins*
   ;; capability runtime (math/nl/local-user)
   #:symbol-runtime-boot!
   #:symbol-capability-enabled-p
   #:symbol-tree-model
   #:symbol-toggle!
   #:symbol-default-enable!
   #:symbol-math-answer
   #:symbol-nl-chitchat
   #:symbol-nl-concept
   #:symbol-nl-pick
   #:symbol-nl-bank-add!
   #:symbol-local-user-answer
   #:symbol-local-user-facts
   #:symbol-local-learning-p
   #:symbol-loaded-summary
   #:symbol-catalog-download!
   #:*symbol-default-ids*
   #:*nl-phrase-banks*
   ;; sealed symbols (open-sealed + private-sealed)
   #:make-symbol-seal-header
   #:symbol-seal-header-validate
   #:symbol-seal!
   #:symbol-seal-sign!
   #:symbol-seal-verify
   #:symbol-seal-decrypt-body
   #:symbol-seal-load!
   #:symbol-seal-read-header
   #:symbol-seal-dir-p
   #:symbol-seal-body-opaque-p
   #:symbol-marketplace-load-index!
   #:symbol-marketplace-register!
   #:symbol-marketplace-save-index!
   #:symbol-marketplace-check
   #:symbol-source-kit-new!
   #:symbol-source-kit-read
   #:symbol-source-kit-ingest!
   #:symbol-source-kit-ingest-book!
   #:symbol-train-from-kit!
   #:symbol-build!
   #:symbol-source-kit-root
   #:symbol-sealed-root
   #:make-symbol-source-manifest
   ;; 4.3 hybrid CLS cognitive unit
   #:cognitive-unit
   #:cognitive-turn
   #:epoch-cognitive-step
   #:hybrid-demo
   #:hippocampus-encode!
   #:hippocampus-clear!
   #:hippocampus-size
   #:hippocampus-episodes
   #:hippocampus-sample-prioritized
   #:hippocampus-interleaved-batches
   #:neocortex-consolidate!
   #:sleep-consolidate!
   #:hybrid-forget-test
   #:hybrid-coupled-propose
   #:hybrid-coupled-accept-p
   #:register-coupled-templates!
   #:*coupled-accept-templates*
   #:episode-summary-key
   #:hybrid-a-token-retention
   #:hybrid-separation-probe
   #:hybrid-long-context-train!
   #:hybrid-offline-schedule!
   #:hybrid-plan-explain
   #:curriculum-ladder-run
   #:trust-policy-allows-p
   #:nn-enable-path-policy
   #:hybrid-teach-policy
   #:hybrid-metrics
   #:hybrid-metrics-reset!
   #:hybrid-metrics-adjust!
   #:make-explain-object
   #:tms-recheck
   #:nn-disable-path-meta
   #:*online-learn-enabled*
   #:*online-lm-name*
   #:*replay-enabled*
   #:*replay-k*
   #:*train-max-batches-cap*
   #:*train-max-epochs-cap*
   #:*separation-retention-threshold*
   #:*hybrid-thesis*
   #:install-hybrid-tools
   #:symbol-marketplace-catalog
   #:symbol-marketplace-install
   #:society-trust!
   #:society-trust-p
   #:society-trusted-send
   #:durable-save-hybrid!
   #:durable-load-hybrid!)
  (:documentation
   "Metis 1.0 — production introspective multi-agent cognitive architecture.
    Code is data; minds reason, plan (STRIPS+HTN), maintain truth, learn, and collaborate."))

(in-package :metis)

(pushnew :metis-production *features*)
