;;;; world.lisp — persist and restore mind images as s-expressions
(in-package :metis)

(defun %world-path (name)
  (merge-pathnames
   (format nil "~A.mind.lisp" name)
   (get-config :world-dir
               (merge-pathnames "worlds/"
                                (asdf:system-source-directory :metis)))))

(defun save-world (mind &optional (name "default"))
  (let* ((m (ensure-mind mind))
         (path (%world-path name))
         (snap
          (list :metis-world 1
                :saved (now-iso)
                :cycle (mind-cycle m)
                :goals (mind-goals m)
                :kb (kb-snapshot (mind-kb m))
                :frames (fs-snapshot (mind-frames m))
                :episodes
                (mapcar (lambda (e)
                          (list :id (ep-id e)
                                :time (ep-time e)
                                :situation (ep-situation e)
                                :goals (ep-goals e)
                                :action (ep-action e)
                                :outcome (ep-outcome e)
                                :valence (ep-valence e)
                                :tags (ep-tags e)
                                :meta (ep-meta e)))
                        (emem-episodes (mind-em m)))
                :skills
                (mapcar (lambda (s)
                          (list :name (skill-name s)
                                :params (skill-params s)
                                :preconds (skill-preconds s)
                                :body (skill-body s)
                                :kind (skill-kind s)
                                :source (skill-source s)
                                :utility (skill-utility s)
                                :uses (skill-uses s)
                                :successes (skill-successes s)
                                :meta (skill-meta s)))
                        (pm-all (mind-pm m)))
                :operators
                (mapcar (lambda (op)
                          (list :name (op-name op)
                                :params (op-params op)
                                :preconds (op-preconds op)
                                :add (op-add-list op)
                                :del (op-del-list op)
                                :cost (op-cost op)))
                        (pd-operators-list (mind-domain m))))))
    (ensure-directories-exist path)
    (with-open-file (out path :direction :output
                              :if-exists :supersede
                              :if-does-not-exist :create)
      (with-standard-io-syntax
        (let ((*package* (find-package :metis))
              (*print-pretty* t)
              (*print-readably* t))
          (prin1 snap out)
          (terpri out))))
    (mind-trace-push m :save-world name (namestring path))
    (namestring path)))

(defun load-world (mind &optional (name "default"))
  (let* ((m (ensure-mind mind))
         (path (%world-path name)))
    (unless (probe-file path)
      (error 'metis-error
             :message (format nil "world not found: ~A" path)))
    (let ((snap (with-open-file (in path)
                  (let ((*package* (find-package :metis)))
                    (read in)))))
      (unless (eq (first snap) :metis-world)
        (error 'metis-error :message "invalid world file"))
      (kb-restore (mind-kb m) (getf snap :kb))
      (fs-restore (mind-frames m) (getf snap :frames))
      (setf (mind-goals m) (getf snap :goals))
      (setf (mind-cycle m) (or (getf snap :cycle) 0))
      ;; episodes
      (setf (emem-episodes (mind-em m)) nil
            (emem-next-id (mind-em m)) 0)
      (dolist (e (reverse (getf snap :episodes)))
        (em-remember (mind-em m)
                     :situation (getf e :situation)
                     :goals (getf e :goals)
                     :action (getf e :action)
                     :outcome (getf e :outcome)
                     :valence (or (getf e :valence) 0.0)
                     :tags (getf e :tags)
                     :meta (getf e :meta)))
      ;; skills
      (clrhash (pmem-skills (mind-pm m)))
      (dolist (s (getf snap :skills))
        (pm-install (mind-pm m)
                    (make-skill
                     :name (getf s :name)
                     :params (getf s :params)
                     :preconds (getf s :preconds)
                     :body (getf s :body)
                     :kind (or (getf s :kind) :procedure)
                     :source (or (getf s :source) :restored)
                     :utility (or (getf s :utility) 0.0)
                     :uses (or (getf s :uses) 0)
                     :successes (or (getf s :successes) 0)
                     :meta (getf s :meta))))
      ;; operators
      (clrhash (pd-operators (mind-domain m)))
      (dolist (op (getf snap :operators))
        (pd-define-operator (mind-domain m)
                            (getf op :name)
                            :params (getf op :params)
                            :preconds (getf op :preconds)
                            :add (getf op :add)
                            :del (getf op :del)
                            :cost (getf op :cost)))
      (mind-trace-push m :load-world name)
      m)))
